### ISSUE TITLE
feat: Add a complex example using multiple localizations and configuration with nested componets

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-website#108]
**What would you like to be added**:

Components like this one:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/open-component-model/podify
  version:
    semver: v1.0.3-dev
  repository:
    url: ghcr.io/skarlso/ocm-podify
    secretRef:
      name: oci-creds
  verify: []
  references:
    expand: true

```

with a component ref like this:

```yaml
components:
# -- product component
- name: github.com/open-component-model/podinfo
  version: 1.0.0
  provider:
    name: open-component-model
  componentReferences:
  - name: backend
    componentName: github.com/open-component-model/podinfo/backend
    version: 1.0.0
  - name: frontend
    componentName: github.com/open-component-model/podinfo/frontend
    version: 1.0.8
  - name: redis
    componentName: github.com/open-component-model/redis
    version: 1.0.0
# -- backend component
- name: github.com/open-component-model/podinfo/backend
  version: 1.0.0
  provider:
    name: open-component-model
  resources:
  - name: config
    type: configdata.ocm.software
    input:
      type: file
      mediaType: application/yaml
      path: ./app/backend/config.yaml
      compress: true
  - name: instructions
    type: PlainText
    input:
      type: file
      mediaType: text/markdown
      path: ./app/backend/README.md
      compress: true
  - name: image
    relation: external
    type: ociImage
    version: 6.2.0
    access:
      type: ociArtifact
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
  - name: manifests
    type: kustomize.ocm.fluxcd.io
    input:
      type: dir
      path: ./app/backend/manifests
      compress: true
# -- frontend component
- name: github.com/open-component-model/podinfo/frontend
  version: 1.0.8
  provider:
    name: open-component-model
  resources:
  - name: config
    type: configdata.ocm.software
    input:
      type: file
      mediaType: application/yaml
      path: ./app/frontend/config.yaml
      compress: true
  - name: instructions
    type: PlainText
    version: 1.0.7
    input:
      type: file
      mediaType: text/markdown
      path: ./app/frontend/README.md
      compress: true
  - name: image
    relation: external
    type: ociImage
    version: 6.2.0
    access:
      type: ociArtifact
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
  - name: manifests
    type: kustomize.ocm.fluxcd.io
    input:
      type: dir
      path: ./app/frontend/manifests
      compress: true
# -- redis component
- name: github.com/open-component-model/redis
  version: 1.0.0
  provider:
    name: open-component-model
  resources:
  - name: config
    type: configdata.ocm.software
    input:
      type: file
      mediaType: application/yaml
      path: ./redis/config.yaml
      compress: true
  - name: instructions
    type: PlainText
    input:
      type: file
      mediaType: text/markdown
      path: ./redis/README.md
      compress: true
  - name: image
    relation: external
    type: ociImage
    version: 6.0.1
    access:
      type: ociArtifact
      imageReference: redis:6.0.1
  - name: manifests
    type: kustomize.ocm.fluxcd.io
    input:
      type: dir
      path: ./redis/manifests
      compress: true
```

**Why is this needed**:

These complex component versions aren't really explained and how the pieces fit together and why. Especially not if doing these things by hand. We use product controller or unpacker to deal with these, but there aren't any explanations on the moving parts that would detail how things fit together.
