### ISSUE TITLE
content of `components.yaml` at guides/structuring-software-with-ocm/#input-specification -> invalid component spec 1[1]: component.name

### ISSUE THREAD

**Issue by sTb1337** [open-component-model/ocm-website#187]
**What happened**:
I try to start with this guide: https://ocm.software/docs/guides/structuring-software-with-ocm/#input-specification:

Q: Is content of `components.yaml` valid?

Because i get Error: components.yaml: `invalid component spec 1[1]: component.name: Does not match pattern '^[a-z][-a-z0-9]*([.][a-z][-a-z0-9]*)*[.][a-z]{2,}(/[a-z][-a-z0-9_]*([.][a-z][-a-z0-9_]*)*)+$'`

Using example of `ocm add componentversions --help`  it works:

```
name: ocm.software/demo/test
version: 1.0.0
provider:
  name: ocm.software
  labels:
    - name: city
      value: Karlsruhe
labels:
  - name: purpose
    value: test
resources: 
  - name: data
    type: PlainText
    input:
      type: binary
      data: IXN0cmluZ2RhdGE=
```

```
ocm add componentversions --create --file target --settings settings.yaml components-2.yaml
processing components-2.yaml...
  processing document 1...
    processing index 1
found 1 component
adding component ocm.software/demo/test:1.0.0...
  adding resource PlainText: "name"="data","version"="<componentversion>"...
➜  ocm-hello-world git:(main) ✗ ocm get component -o yaml ./target 
---
component:
  componentReferences: []
  creationTime: "2024-03-07T10:56:28Z"
  labels:
  - name: purpose
    value: test
  name: ocm.software/demo/test
  provider: '{"name":"ocm.software","labels":[{"name":"city","value":"Karlsruhe"}]}'
  repositoryContexts: []
  resources:
  - access:
      localReference: sha256:2b37b8604925c0dffb3e609cb29e31d5b1b46f174290eee1341fc20d30dc3c33
      mediaType: application/octet-stream
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 2b37b8604925c0dffb3e609cb29e31d5b1b46f174290eee1341fc20d30dc3c33
    name: data
    relation: local
    type: PlainText
    version: 1.0.0
  sources: []
  version: 1.0.0
meta:
  schemaVersion: v2
```

** Solution***:

Do not use "-" or capital letters within names e.g.
```
- name: ${COMPONENT_NAME_PREFIX}/microblog-deployment
```

```
- name: ${COMPONENT_NAME_PREFIX}/microblogdeployment
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
